version: '3'
services:
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment: 
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - BUNDLE_PATH=/bundle/vendor
    volumes:
      - .:/odontoclin-server
      - bundle_path:/bundle
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  bundle_path:
  postgres-data: