name: odontclin-server

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clinica_server_test
        ports:
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install PostgreSQL client
      run: sudo apt-get install libpq-dev

    - name: DB Configuration
      env:
        DB_HOST: localhost
        DB_USER: postgres
        DB_PASSWORD: postgres
        DEVISE_JWT_SECRET_KEY: 405a8ac8206453e50545197cd1fb69daed71672bce443f76e54b9defa6ceb8f5c9e9a88f0fe426b5567192d55b93b5d8c1ac9d619b0a109d0fd4328c6108ff41
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:setup
    - name: Run tests
      env:
        DB_HOST: localhost
        DB_USER: postgres
        DB_PASSWORD: postgres
        DEVISE_JWT_SECRET_KEY: 405a8ac8206453e50545197cd1fb69daed71672bce443f76e54b9defa6ceb8f5c9e9a88f0fe426b5567192d55b93b5d8c1ac9d619b0a109d0fd4328c6108ff41
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        RAILS_ENV: test
      run: |
        bundle exec rspec
